import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/Navigation";
import { CartProvider } from "./_providers/CartContext";
import { AuthProvider } from "@/app/_providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { getUserFromServer } from "@/lib/getUserFromServer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, accessToken } = await getUserFromServer();
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden overflow-y-hidden min-h-screen`}
      >
        <AuthProvider initialToken={accessToken} initialUser={user}>
          <CartProvider>
            <Toaster
              toastOptions={{
                classNames: {
                  error: "!bg-destructive !text-white !border-0",
                  success: "",
                },
              }}
            />
            <Navigation />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
